server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: picture-service-app
          uri: lb://PICTURE-SERVICE-APP
          predicates:
            - Path=/api/v1/picture/**
        - id: bazaar-backend-api-app
          uri: lb://BAZAAR-BACKEND-API
          predicates:
            - Path=/api/v1/**